### ISSUE TITLE
Problem with female symbol in ascii?

### ISSUE THREAD

**Issue by sanderquirynen** [Cy4n1d3/PokeminerSpawns#1]
I'm getting following error:

```
Traceback (most recent call last):
  File "spawn_location.py", line 73, in <module>
    print "#{:03} {}".format(poke_id, pokemonsJSON[str(poke_id)])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2640' in position 7: ordinal not in range(128)
```

Apparently \u2640 is the female-symbol (I'm guessing from Nidoran)

**Comment by Cy4n1d3** [comment]
Either your console does not support UTF-8 or python just does not recognize it does.
I've pushed a possible workaround in 13b7e5d4affc982064974a8485d2160bb734e689.
Hopefully your console does support UTF-8 (actually most do) and this fixes it.
If it does not I'll have to look around a bit, as I can't reproduce it locally right now.

**Comment by ferazambuja** [comment]
I'm getting the same here. UTF-8 is enabled in my terminal.
The problem is the "\". Going to look if there is a way to replace.

**Comment by Cy4n1d3** [comment]
The problem are unicode characters inside the Pokemon json (which there is nothing wrong with) and the default Python encoding of 'ascii', which does not support those characters.
Please try setting `export PYTHONIOENCODING=utf8` before running the script and report back your results.
Example:
```
export PYTHONIOENCODING=utf8
python spawn_location.py "1.2, 3.4" mytown en
```
This should fix the problem temporarily.
I'll push a proper fix soon.

**Comment by ferazambuja** [comment]
Yes, I used the id as a quick fix to deal with the negative lat and long.

**Comment by Cy4n1d3** [comment]
@sanderquirynen this is not a problem of your json file!
Python with version lower than 3 simply does not handle unicode characters correctly by default.
The implementation of 'ascii' chars as default charset in Python happened over a decade ago....
Please revert your pokemon.en.json back to default by replacing it with the original file from Pokeminer.

@sanderquirynen @ferazambuja 
27cc5304567100a9a5a1860025587a05fc93bd1e should fix the errors you see inside the console window.
At least that's what I'm hoping, as there is no easy way to tell for me :) If you're still having problems, please report back with the corresponding line and the error you're getting!

**Comment by ferazambuja** [comment]
I'm still getting. To reproduce just change a few pokemon_id on your db to 29 and 32.

**Comment by ferazambuja** [comment]
So far changing decode to encode fix the print issues. I'm also playing with
pokemonsJSON[str(t[2]['id'])].encode('utf-8')).
 Now the error is in the write html:
Traceback (most recent call last):
  File "spawn_location.py", line 161, in <module>
    f.write(html)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2640' in position 8987734: ordinal not in range(128)

**Comment by Cy4n1d3** [comment]
I couldn't reproduce even if I print the whole content of pokemon.en.json (all ~700 pokemon) line by line - including each and every unicode character.
It doesn't occur on my Windows Server 2008 R2 and neither on my Windows 10 machine.

Server 2008 R2 console output of pokemon 29 + 32:
![image](https://cloud.githubusercontent.com/assets/873577/17272345/4e506f6a-5694-11e6-9f21-ef5689345249.png)
Windows 10 console output of pokemon 29 + 32:
![image](https://cloud.githubusercontent.com/assets/873577/17272349/7f52b938-5694-11e6-95c1-c110ec1812ac.png)
---
I could reproduce the error inside a fresh, badly configured VM now.
decode/encode was a typo on my side, yes...
Still, I dislike that solution, as it means manual sanitizing of every print we do.

Seems like these things are a pain in the ass with Python... I'll conduct some more research and see if I can find a better solution.

**Comment by ferazambuja** [comment]
Did work with :
#!/usr/bin/python
# -*- coding: utf-8 -*-
https://www.python.org/dev/peps/pep-0263/

**Comment by ferazambuja** [comment]
Here is my workaround: https://github.com/Cy4n1d3/PokeminerSpawns/pull/3/commits/062622eda75698886e8f52dacbe3c5623d95fdc9

Python hates utf-8 had to use .encode(utf-8) for everything. Everything seems to work besides showing the poke_id on the terminal screen.

**Comment by Cy4n1d3** [comment]
This does not help in every case though.
I've got `# -*- coding: utf-8 -*-`in my local version as well, still get errors.

**Comment by ferazambuja** [comment]
I know I just left there. Did you try with my changes? To basically encode everything...

**Comment by Cy4n1d3** [comment]
Yes I did, left a comment on the PR. Randomly encoding everything using a fixed encoding is not a good solution I think - it breaks correct display of unicode names on html pages for example. And that's just something I could spot quickly, who knows what else might break later on.

**Comment by ferazambuja** [comment]
The HTML files lacked a proper head. I add to it and now shows correctly. Not saying that is the best solution.

**Comment by Cy4n1d3** [comment]
I've identified a few underlying problems and fixed some of them.
For me the Pokemon containing unicode chars are now working fine.
Please check out the latest commit and report back your results :)

**Comment by ferazambuja** [comment]
Yep it works!

**Comment by plague180** [comment]
I tried the latest commit and I still get the same error

**Comment by ferazambuja** [comment]
I'm sorry for that. A workaround is modified the symbols on the json file for now.

**Comment by Cy4n1d3** [comment]
@plague180 can you get me the stacktrace?

**Comment by Pikachurin** [comment]
`Traceback (most recent call last):
  File "spawn_location.py", line 89, in <module>
    print u"#{:03} {}".format(poke_id, pokeData[str(poke_id)])
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2640' in position 12: character maps to <undefined>`

Getting this with the latest code. It worked when I changed the symbols in pokemon.en.json to text instead though but still seems to be problems with the female and male symbols

**Comment by plague180** [comment]
![trace](https://cloud.githubusercontent.com/assets/8250386/17275663/cbab8336-56cc-11e6-8f0c-3c38942c562e.png)

**Comment by plague180** [comment]
So I decided to try and work on this today. Please keep in mind this is my first time using python, I mostly use C#, so I'm sorry if i did something I shouldn't. The two traces I get when I use the current commit are
![trace1](https://cloud.githubusercontent.com/assets/8250386/17310460/c9d49634-5801-11e6-9275-853a3a526d5c.png)
![trace2](https://cloud.githubusercontent.com/assets/8250386/17310462/cd9db3ae-5801-11e6-96eb-fdab20cd6d73.png)
I added .encode('ascii', 'ignore').decode("utf-8") to those lines, since I saw you said not to use encode. It is now working for me again and it does show the symbols on the webpage (I saw that was a concern) Let me know what you think

**Comment by plague180** [comment]
So I refreshed the page to see if anyone commented on my fix from earlier and my comment is missing, but I'm not sure if I ever submitted it or not. Either way the gist was where I'm getting these errors: 
![trace1](https://cloud.githubusercontent.com/assets/8250386/17312324/18d715ce-580f-11e6-8edc-0fcd303bf2dc.png)
![trace2](https://cloud.githubusercontent.com/assets/8250386/17312323/18d46e00-580f-11e6-844e-8a02b226f2bc.png)

plus on 157. I put .encode('ascii', 'ignore').decode("utf-8") and now it all works for me. I'm new to python (use c# 99% of the time) and I don't know if its bad to do that (I saw no using encode, and that the html still needed the symbol) Let me know if this is ok and if it works. But now all my problems are gone.

**Comment by Cy4n1d3** [comment]
We might have to go that route or switch to Python 3.x, which is unlikely as many people still use 2.7.

**Comment by Cy4n1d3** [comment]
This should only affect the print I hope, so html should be fine. I'll have another look at this...
